export const SET_DRAWER_CONTEXT = 'SET_DRAWER_CONTEXT';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const SIGNING_IN = 'SIGNING_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADDING_CATEGORY = 'ADDING_CATEGORY';
