export const SET_DRAWER_CONTEXT = 'SET_DRAWER_CONTEXT';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const SIGNING_IN = 'SIGNING_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CATEGORY_FAILURE = 'CATEGORY_FAILURE';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CLOSE_SUCCESS_SNACKBAR = 'CLOSE_SUCCESS_SNACKBAR';
export const CLOSE_FAILURE_SNACKBAR = 'CLOSE_FAILURE_SNACKBAR';
export const ADDING_CATEGORY = 'ADDING_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
