export const SET_DRAWER_CONTEXT = 'SET_DRAWER_CONTEXT';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const SIGNING_IN = 'SIGNING_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CLOSE_SUCCESS_SNACKBAR = 'CLOSE_SUCCESS_SNACKBAR';
export const CLOSE_FAILURE_SNACKBAR = 'CLOSE_FAILURE_SNACKBAR';

export const ADDING_CATEGORY = 'ADDING_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORY_FAILURE = 'CATEGORY_FAILURE';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';

export const ADDING_PRODUCT = 'ADDING_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';

// export const GET_USER = 'GET_USER';
// export const GET_ALL_USERS = 'GET_ALL_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_SUCCESS = 'USER_SUCCESS';
