#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Change to Root Directory
cd ..

# Build Docker Image
docker build -t avidyarth/inventory-management-client .

# Push Latest Image to Repository
docker push avidyarth/inventory-management-client